name: Test CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: go mod tidy
      - name: WriteGoList
        run: go list -json -m all > go.list
      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main
      - run: go vet -x .
      - run: go test -covermode=atomic -coverprofile="coverage.out" .
      - name: Coveralls
        run: bash <(curl -s https://codecov.io/bash)
